language: go
go: 
 - 1.8
 - 1.9
 - tip

install:
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - $HOME/gopath/bin/goveralls -v -service=travis-ci -repotoken $COVERALLS_TOKEN